/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author FazalUr
 */
public class SecondPage extends javax.swing.JFrame {

    /**
     * Creates new form SecondPage
     */
    public SecondPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator Menu");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Sign Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 450, 150, 30);

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("Register New Customer");
        jButton2.setPreferredSize(new java.awt.Dimension(79, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(560, 440, 220, 30);

        jButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton3.setText("Delete Existing Customer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(560, 400, 220, 30);

        jButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton4.setText("Update Existing Customer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(560, 360, 220, 30);

        jButton5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton5.setText("Search Existing Customer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(560, 320, 220, 30);

        jButton6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton6.setText("View All Customers");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(560, 280, 220, 30);

        jButton7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton7.setText("View All Rooms");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(560, 80, 220, 30);

        jButton8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton8.setText("Search Existing Room");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(560, 120, 220, 30);

        jButton9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton9.setText("Delete Existing Room");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(560, 160, 220, 30);

        jButton10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton10.setText("Update Existing Room");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(560, 200, 220, 30);

        jButton11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton11.setText("Register New Room");
        jButton11.setPreferredSize(new java.awt.Dimension(79, 23));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(560, 240, 220, 30);

        jButton12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton12.setText("View rooms available");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(20, 180, 240, 30);

        jButton13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton13.setText("Book a room");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(20, 60, 240, 30);

        jButton14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton14.setText("Calculate Bill");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(20, 100, 240, 30);

        jButton15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton15.setText("View total Earnings");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(20, 140, 240, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Administrator Menu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(610, 50, 130, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPackage/002.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Main.H1.getCustomers()[Main.H1.getCustomerCounter()].setId("205");
        Main.H1.getCustomers()[Main.H1.getCustomerCounter()].setAddress(JOptionPane.showInputDialog(Main.P2, "Enter address of customer: "));
        Main.H1.getCustomers()[Main.H1.getCustomerCounter()].setName(JOptionPane.showInputDialog(Main.P2, "Enter name of customer: "));
        Main.H1.setCustomerCounter(Main.H1.getCustomerCounter()+1);
        JOptionPane.showMessageDialog(Main.P2, "New customer created successfully.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(Main.P2, "Are you sure to sign out!") == 0)
        {
            Main.P2.setVisible(false);
            Main.P1.setVisible(true);            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (Main.H1.getCustomerCounter()>0)
        {
            String A = JOptionPane.showInputDialog(Main.P2, "Enter name of customer to delete: ");
            for (int i=0;i<Main.H1.getCustomerCounter();i++)
            {
                if (Main.H1.getCustomers()[i].getName().equalsIgnoreCase(A))
                {
                    Main.H1.getCustomers()[i].equals(null);
                    JOptionPane.showMessageDialog(Main.P2, "Customer deleted successfully."); 
                    Main.H1.setCustomerCounter(Main.H1.getCustomerCounter()-1);
                    break;
                }
                else if (i==Main.H1.getCustomerCounter()-1)
                {
                    JOptionPane.showMessageDialog(Main.P2, "Sorry, no such customer found!");    
                }
            }            
        }
        else
        {
            JOptionPane.showMessageDialog(Main.P2, "Sorry, no such customer found!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String A = JOptionPane.showInputDialog(Main.P2,"Enter room id to update: ");
        if (Main.H1.getRoomCounter()>0)
        {
            for (int i=0;i<Main.H1.getRoomCounter();i++)
            {
                if (Main.H1.getRooms()[i].getNo() == Integer.parseInt(A))
                {
                    Main.H1.getRooms()[i].setCharges(Double.parseDouble(JOptionPane.showInputDialog(Main.P2, "Enter charges to update: ")));
                    Main.H1.getRooms()[i].setFacilities(JOptionPane.showInputDialog(Main.P2, "Enter facilities to update: "));
                    JOptionPane.showMessageDialog(Main.P2, "Room updated successfully.");
                    break;
                }
                else if (i == Main.H1.getRoomCounter()-1)
                {
                    JOptionPane.showMessageDialog(Main.P2, "Sorry. No room found for query!");
                }
            }            
        }
        else
        {
            JOptionPane.showMessageDialog(Main.P2, "Sorry. No room found for query!");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        Main.H1.getRooms()[Main.H1.getRoomCounter()].setNo(Main.H1.getRoomCounter()+100);
        Main.H1.getRooms()[Main.H1.getRoomCounter()].setCharges(Double.parseDouble(JOptionPane.showInputDialog(Main.P2, "Enter charges for room: ")));
        Main.H1.getRooms()[Main.H1.getRoomCounter()].setFacilities(JOptionPane.showInputDialog(Main.P2, "Enter facilities available in room: "));
        Main.H1.getRooms()[Main.H1.getRoomCounter()].setNoOfPeoples(Integer.parseInt(JOptionPane.showInputDialog(Main.P2, "Enter no. of peoples that can reside in room: ")));
        Main.H1.getRooms()[Main.H1.getRoomCounter()].setStatus(true);
        Main.H1.getRooms()[Main.H1.getRoomCounter()].setAvailableIn(0);
        JOptionPane.showMessageDialog(Main.P2, "New room added successfully.");
        Main.H1.setRoomCounter(Main.H1.getRoomCounter()+1);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (Main.H1.getRoomCounter()>0)
        {
            for (int i=0;i<Main.H1.getRoomCounter();i++)
            {
                JOptionPane.showMessageDialog(Main.P2, "\nRoom no: " + Main.H1.getRooms()[i].getNo() + "\nNo of Peoples: " + Main.H1.getRooms()[i].getNoOfPeoples() + "\nCharges: " + Main.H1.getRooms()[i].getCharges() + "\nStatus: " + Main.H1.getRooms()[i].isStatus() + "\nFacilities: " + Main.H1.getRooms()[i].getFacilities() + "\nCustomer Id: " + Main.H1.getRooms()[i].getCustomerId() + "\nAvailable in: " + Main.H1.getRooms()[i].getAvailableIn());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(Main.P2, "Sorry. No room found for query!");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String A = JOptionPane.showInputDialog(Main.P2,"Enter room id to search: ");
        if (Main.H1.getRoomCounter()>0)
        {
            for (int i=0;i<Main.H1.getRoomCounter();i++)
            {
                if (Main.H1.getRooms()[i].getNo() == Integer.parseInt(A))
                {
                    JOptionPane.showMessageDialog(Main.P2, "\nRoom no: " + Main.H1.getRooms()[i].getNo() + "\nNo of Peoples: " + Main.H1.getRooms()[i].getNoOfPeoples() + "\nCharges: " + Main.H1.getRooms()[i].getCharges() + "\nStatus: " + Main.H1.getRooms()[i].isStatus() + "\nFacilities: " + Main.H1.getRooms()[i].getFacilities() + "\nCustomer Id: " + Main.H1.getRooms()[i].getCustomerId() + "\nAvailable in: " + Main.H1.getRooms()[i].getAvailableIn());
                    break;
                }
                else if (i == Main.H1.getRoomCounter()-1)
                {
                    JOptionPane.showMessageDialog(Main.P2, "Sorry. No room found for query!");
                }
            }            
        }
        else
        {
            JOptionPane.showMessageDialog(Main.P2, "Sorry. No room found for query!");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String A = JOptionPane.showInputDialog(Main.P2,"Enter room id to delete: ");
        for (int i=0;i<Main.H1.getRoomCounter();i++)
        {
            if (Main.H1.getRooms()[i].getNo() == Integer.parseInt(A))
            {
                JOptionPane.showMessageDialog(Main.P2, "\nRoom no: " + Main.H1.getRooms()[i].getNo() + "\nNo of Peoples: " + Main.H1.getRooms()[i].getNoOfPeoples() + "\nCharges: " + Main.H1.getRooms()[i].getCharges() + "\nStatus: " + Main.H1.getRooms()[i].isStatus() + "\nFacilities: " + Main.H1.getRooms()[i].getFacilities() + "\nCustomer Id: " + Main.H1.getRooms()[i].getCustomerId() + "\nAvailable in: " + Main.H1.getRooms()[i].getAvailableIn());
                if (JOptionPane.showConfirmDialog(Main.P2, "Are you sure to delete this room: ")==0)
                {
                    JOptionPane.showMessageDialog(Main.P2, "Rooom no :" + Main.H1.getRooms()[i].getNo() + " deleted successfully.");
                    Main.H1.getRooms()[i].equals(null);
                    Main.H1.setRoomCounter(Main.H1.getRoomCounter()-1);
                    break;
                }
            }
            else if (i == Main.H1.getRoomCounter()-1)
            {
                JOptionPane.showMessageDialog(Main.P2, "Sorry. No room found for query!");
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (Main.H1.getCustomerCounter() > 0)
        {
            for (int i=0;i<Main.H1.getCustomerCounter();i++)
            {
                JOptionPane.showMessageDialog(Main.P2, "\nName: " + Main.H1.getCustomers()[i].getName() + "\nId: " + Main.H1.getCustomers()[i].getId() + "\nAddress: " + Main.H1.getCustomers()[i].getAddress() + "\nBills payed: " + Main.H1.getCustomers()[i].isBillPayed() + "\nAdvance: " + Main.H1.getCustomers()[i].getAdvance() + "\nPending: " + Main.H1.getCustomers()[i].getPending() + "\nBalance: " + Main.H1.getCustomers()[i].getTotalBalance() + "\nStay days: " + Main.H1.getCustomers()[i].getDays());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(Main.P2, "No such customer found.");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (Main.H1.getCustomerCounter() > 0)
        {
            String A = JOptionPane.showInputDialog(Main.P2, "Enter name of customer to search: ");
            for (int i=0;i<Main.H1.getCustomerCounter();i++)
            {
                if (Main.H1.getCustomers()[i].getName().equalsIgnoreCase(A))
                {
                    JOptionPane.showMessageDialog(Main.P2, "\nName: " + Main.H1.getCustomers()[i].getName() + "\nId: " + Main.H1.getCustomers()[i].getId() + "\nAddress: " + Main.H1.getCustomers()[i].getAddress() + "\nBills payed: " + Main.H1.getCustomers()[i].isBillPayed() + "\nAdvance: " + Main.H1.getCustomers()[i].getAdvance() + "\nPending: " + Main.H1.getCustomers()[i].getPending() + "\nBalance: " + Main.H1.getCustomers()[i].getTotalBalance() + "\nStay days: " + Main.H1.getCustomers()[i].getDays());
                    break;
                }
                else if (i==Main.H1.getCustomerCounter()-1)
                {
                    JOptionPane.showMessageDialog(Main.P2, "Sorry, no such customer found!");         
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(Main.P2, "Sorry, no such customer found!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (Main.H1.getCustomerCounter()>0)
        {
            String A = JOptionPane.showInputDialog(Main.P2, "Enter name of customer to update: ");
            for (int i=0;i<Main.H1.getCustomerCounter();i++)
            {
                if (Main.H1.getCustomers()[i].getName().equalsIgnoreCase(A))
                {
                    Main.H1.getCustomers()[i].setAddress(JOptionPane.showInputDialog(Main.P2, "Enter address of customer: "));                    
                    Main.H1.getCustomers()[i].setName(JOptionPane.showInputDialog(Main.P2, "Enter name of customer: "));
                    Main.H1.getCustomers()[i].setId(JOptionPane.showInputDialog(Main.P2, "Enter id of customer: "));
                    JOptionPane.showMessageDialog(Main.P2, "Customer data updated successfully."); 
                    break;
                }
                else if (i==Main.H1.getCustomerCounter()-1)
                {
                    JOptionPane.showMessageDialog(Main.P2, "Sorry, no such customer found!");         
                }
            }            
        }
        else
        {
            JOptionPane.showMessageDialog(Main.P2, "Sorry, no such customer found!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        String A = JOptionPane.showInputDialog(Main.P2, "Enter customer id for which you want to book room: ");
        
        if (Main.H1.getCustomerCounter()>0)
        {            
            for (int i=0;i<Main.H1.getCustomerCounter();i++)
            {
                if (Main.H1.getCustomers()[i].getId().equalsIgnoreCase(A))
                {
                    int B = Integer.parseInt(JOptionPane.showInputDialog(Main.P2, "Enter room no to book for customer: "));
                    for (int j=0;j<Main.H1.getRoomCounter();j++)
                    {
                        if (B == Main.H1.getRooms()[i].getNo())
                        {
                            Main.H1.setTotalEarnings(Main.H1.getTotalEarnings()+Main.H1.getRooms()[j].getCharges());
                            Main.H1.getRooms()[j].setStatus(false);
                            JOptionPane.showMessageDialog(Main.P2, "Room booked successfully.");
                            Main.H1.getCustomers()[i].setTotalBalance(Main.H1.getCustomers()[i].getTotalBalance() + Main.H1.getRooms()[j].getCharges());
                            JOptionPane.showMessageDialog(Main.P2, "\n----- Total Bill --- Invoice ----\n\n--- Customer Details ---\n\nCustomer name: " + Main.H1.getCustomers()[i].getName() + "\nAddress: " + Main.H1.getCustomers()[i].getAddress() + "\nTotal Balance: " + Main.H1.getCustomers()[i].getTotalBalance() + "\n\n----- Room Details -----\n\nRoom no: " + Main.H1.getRooms()[j].getNo() + "\nCharges: " + Main.H1.getRooms()[j].getCharges() + "\nFacilities: " + Main.H1.getRooms()[j].getFacilities() + "     " + "\nPersons capacity: " + Main.H1.getRooms()[j].getNoOfPeoples());
                            break;                            
                        }
                        else if (i == Main.H1.getRoomCounter()-1)
                        {
                            JOptionPane.showMessageDialog(Main.P2, "Sorry, no such room found!");                          
                        }
                    }
                }
                else if (i==Main.H1.getCustomerCounter()-1)
                {
                    JOptionPane.showMessageDialog(Main.P2, "Sorry, no such customer found!");       
                }
            }            
        }
        else
        {
            JOptionPane.showMessageDialog(Main.P2, "Sorry, no such customer found!");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        String A = JOptionPane.showInputDialog(Main.P2, "Enter customer id for which you want to book room: ");
        
        if (Main.H1.getCustomerCounter()>0)
        {            
            for (int i=0;i<Main.H1.getCustomerCounter();i++)
            {
                if (Main.H1.getCustomers()[i].getId().equalsIgnoreCase(A))
                {
                    JOptionPane.showMessageDialog(Main.P2, "\n----- Total Bill --- Invoice ----\n\n  --- Customer Details ---\n\nCustomer name: " + Main.H1.getCustomers()[i].getName() + "\nAddress: " + Main.H1.getCustomers()[i].getAddress() + "\nTotal Balance: " + Main.H1.getCustomers()[i].getTotalBalance() );
                }
                else if(i==Main.H1.getCustomerCounter()-1)
                {
                    JOptionPane.showMessageDialog(Main.P2, "Sorry, no such customer record found");
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(Main.P2, "Sorry, no such customer record found");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
            JOptionPane.showMessageDialog(Main.P2, "Total Earnings: " + Main.H1.getTotalEarnings());
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        for (int i=0;i<Main.H1.getRoomCounter();i++)
        {
            if (Main.H1.getRooms()[i].isStatus())
            {
                JOptionPane.showMessageDialog(Main.P2, "\nRoom no: " + Main.H1.getRooms()[i].getNo() + "\nNo of Peoples: " + Main.H1.getRooms()[i].getNoOfPeoples() + "\nCharges: " + Main.H1.getRooms()[i].getCharges() + "\nStatus: " + Main.H1.getRooms()[i].isStatus() + "\nFacilities: " + Main.H1.getRooms()[i].getFacilities() + "\nCustomer Id: " + Main.H1.getRooms()[i].getCustomerId() + "\nAvailable in: " + Main.H1.getRooms()[i].getAvailableIn());
            }
            else if (i == Main.H1.getRoomCounter()-1)
            {
                JOptionPane.showMessageDialog(Main.P2, "No room available right now!");
            }
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
